@startuml
'https://plantuml.com/class-diagram

@startuml
'https://plantuml.com/class-diagram
class Product {
String first
String last
Int salary
+void printLine()
}

class ProductList {
    String name
    Double price
    Int quantity
}

class Product {
    ArrayList<ProductList> products
}

class App {
+{static} void main()
+{static} Boolean isProduct(String in,  Product product)
+{static} void checkProduct(String in,  Product product)
String JSONcontent
String in
Scanner s
Product product
}

App->Product
Product->ProductList


@enduml