@startuml
'https://plantuml.com/class-diagram

class Word {
String word
int freq
}

class App {
+{static}void printOutput()
+{static}void main()
ArrayList<Word> allWords
Scanner inFile
String str
Word newWord
}

App->Word

@enduml